<?php

namespace App\Notifications;

use App\Models\Payroll;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class PayrollDraftCreated extends Notification implements ShouldQueue
{
    use Queueable;

    protected Payroll $payroll;

    protected ?string $actorName;

    /**
     * Create a new notification instance.
     */
    public function __construct(Payroll $payroll, ?string $actorName = null)
    {
        $this->payroll = $payroll;
        $this->actorName = $actorName;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $monthStr = Carbon::parse($this->payroll->salary_month)->format('F Y');

        $message = (new MailMessage)
            ->subject('Draft Payroll '.$monthStr.' Telah Dibuat')
            ->greeting('Halo '.$notifiable->name.',')
            ->line('Draft payroll untuk periode **'.$monthStr.'** telah berhasil digenerate dan saat ini menunggu persetujuan.');

        if ($this->actorName) {
            $message->line('Dibuat oleh: '.$this->actorName);
        }

        return $message
            ->action('Review Payroll', url('/admin/payroll/'.$this->payroll->id))
            ->line('Silakan lakukan peninjauan (review) dan approve draft tersebut agar dapat diproses untuk pembayaran.');
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [
            'category' => 'payroll',
            'title' => 'Payroll Draft Created',
            'body' => 'A new payroll draft for '.Carbon::parse($this->payroll->salary_month)->format('F Y').' has been generated by HR.',
            'action_url' => '/admin/payroll/'.$this->payroll->id,
            'payroll_id' => $this->payroll->id,
            'salary_month' => $this->payroll->salary_month,
            'actor_name' => $this->actorName,
        ];
    }
}
